# test_advanced_parametrization.py
import pytest

# `pytest.param` allows you to apply marks or set IDs to individual parameter sets.
@pytest.mark.parametrize(
    "a, b, expected",
    [
        # A standard parameter set.
        (1, 2, 3),

        # This parameter set is marked as expected to fail (`xfail`).
        pytest.param(5, 5, 11, marks=pytest.mark.xfail(reason="This is an expected failure")),

        # This parameter set is given a custom ID for better reporting.
        pytest.param(10, 20, 30, id="high-numbers-case"),
    ],
)
def test_addition_with_param(a, b, expected):
    """
    Demonstrates the use of pytest.param to customize parameter sets.
    """
    assert a + b == expected


# You can generate test cases programmatically.
def generate_test_data():
    """
    A function that generates test data. In a real application, this could
    come from a file, a database, or an API.
    """
    return [("user", "password123"), ("admin", "secret-key"), ("guest", "guest-pass")]

@pytest.mark.parametrize("username, password", generate_test_data())
def test_login_with_generated_data(username, password):
    """
    This test uses data generated by the `generate_test_data` function.
    """
    assert isinstance(username, str)
    assert isinstance(password, str)


# Stacking multiple `@pytest.mark.parametrize` decorators creates a matrix of test cases.
@pytest.mark.parametrize("x", [1, 2])
@pytest.mark.parametrize("y", ["a", "b"])
@pytest.mark.parametrize("z", [True, False])
def test_matrix_parametrization(x, y, z):
    """
    This test will run for all combinations of x, y, and z.
    Total runs: 2 (for x) * 2 (for y) * 2 (for z) = 8
    """
    print(f"Testing with x={x}, y='{y}', z={z}")
    assert isinstance(x, int)
    assert isinstance(y, str)
    assert isinstance(z, bool)
